### ISSUE TITLE
NbDatePicker: validation fails when using format="dd.MM.yyyy"

### ISSUE THREAD

**Issue by mahnuh** [akveo/nebular#1056]
### Issue type
* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
When using format="dd.MM.yyyy" on NbDatePicker only dates from the 1st till 12th of a month are valid in the formGroup. Using @nebuler/moment and @nebular/date-fns does not make any difference. The issue here seems to be that the form validation does not use the date format I provided. This is the validation error: `nbDatepickerParse: {value: "19.12.2018"}`
As days from 1 to 12 are valid my guess is that days are taken for months?

**Expected behavior:**
19.12.2018 is a valid date when using format="dd.MM.yyyy".

**Steps to reproduce:**
See above.

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: 10.13.0, 6.4.1
OS: macOS
Browser: any
-->
```

**Angular, Nebular**
```
"@angular/core": "7.1.1",
"@nebular/date-fns": "3.0.0",
"@nebular/moment": "3.0.0",
"@nebular/theme": "3.0.0",
```

**Comment by tomadj** [comment]
Hi ! 

Same problem in 3.0.1

**Comment by Tibing** [comment]
Hi Guys! Thanks for reporting this issue. But, As I see it, the solution is quite straightforward. You are trying to set format as `dd.MM.yyyy` but if we refer to [moment](https://momentjs.com/docs/#/parsing/string-format/) or [date-fns](https://date-fns.org/v1.30.1/docs/format) docs we'll find out we have to use all uppercase letters in format, like that: `DD.MM.YYYY`.

I'm closing the issue. If your issue isn't resolved, feel free to reopen it.

**Comment by tomadj** [comment]
Hi @Tibing, 

No uppercase letters don't work :  

`DD.MM.YYYY` --> output  `DD.12.YYYY ` 
`MM.DD.YYYY `--> output  `12/DD/YYYY`

`dd/MM/yyyy`  --> output  `20/12/2018`  OK BUT the formcontrol is not valid as @mahnuh said. 

> As days from 1 to 12 are valid my guess is that days are taken for months 

(With date-fns)

Thank's

**Comment by jromerob** [comment]
Same issue for me .

**Comment by jromerob** [comment]
<nb-datepicker format="yyyy-MM-dd" #startcontrol> </nb-datepicker>
Works right but isn't the correct format for spanish date
![image](https://user-images.githubusercontent.com/11867464/50214959-f2c25f80-0381-11e9-8a86-a238d5c2ef74.png)

**Comment by mahnuh** [comment]
@Tibing as @jromerob and @tomadj put out, it is still an issue. Can you please reopen it?

**Comment by Maxxil** [comment]
Hello,

The same problem for me.

In the ThemeModule I have:

```
  ...NbDateFnsDateModule.forRoot({
    format : 'DD.MM.YYYY',
    parseOptions: { awareOfUnicodeTokens: true },
    formatOptions: { awareOfUnicodeTokens: true }
  }).providers,
  NbDateFnsDateService,
```
In my component.ts I have :

```
constructor(private formBuilder: FormBuilder,
    private dateService: NbDateFnsDateService,
    private route: ActivatedRoute) {

  }

...

    this.plantationForm = this.formBuilder.group({
      exploitant: [null, Validators.required],
      parcelle: [null, Validators.required],
      surface: [null, Validators.required],
      denree: [null, Validators.required],
      densite: [1, Validators.required],
      dateDebut: [today, Validators.required],
      dateFin: [new Date().setMonth(new Date().getMonth() + 4)]
      // dateDebut: [today, Validators.required],
      // dateFin: [today, Validators.required]
    });
```

In my view I have :

![image](https://user-images.githubusercontent.com/15669706/56141187-a3411880-5f9c-11e9-90bf-44b989ca1177.png)


and 

![image](https://user-images.githubusercontent.com/15669706/56141177-9cb2a100-5f9c-11e9-810d-0a78bf4e55e9.png)

In my FormGroup errors I have :
nbDatepickerParse:{value: "18.04.2019"}

It looks like the issue wasn't resolved...

**Comment by romainpurchla** [comment]
Hi,

The problem is here. Any ideas how to solve this ?
```
/**
* We haven't got capability to parse date using formatting without third party libraries.
* */
NbNativeDateService.prototype.parse = function (date, format) {
   return new Date(Date.parse(date));
};
```

**Comment by lukele1607** [comment]
I still get same error when upgrade all package to latest version today

**Comment by riquemoraes** [comment]
I solved the problem of the date invalid, in the format dd / MM / yyyy, as follows:

I installed via npm the package moment:
npm i moment @ types / moment --save

I edited the native-date.service.js file, which in my case is in components \ calendar-kit \ services:

added to line 34: `import * as moment from 'moment';`

changed the NbNativeDateService.prototype.parse function:

`    NbNativeDateService.prototype.parse = function (date, format) {        
        var mydate = moment(date, 'DD/MM/YYYY'); 
        console.log('moment', mydate);
        return new Date(moment(mydate).format("MM/DD/YYYY"));
    };`

Solved for me.

**Comment by bboy437** [comment]
Is there a code sample to watch?

**Comment by luca-nardelli** [comment]
Hey everyone, I've just bumped into this issue and what solved it for me was to install `date-fns v2` instead of v1. Note that v2 was in beta until a couple of days ago so it wasn't installed by default by npm.

I've noticed it due to the call signature of the `parse` function in @nebular/date-fns DateService

**Comment by cuciacik** [comment]
Still same problem v4.4.0. A lot of problems with nebular :|

**Comment by mayanksudden** [comment]
Hi Tibing and yggg,

Still facing same validation issue with nebular 4.5.0., it is latest version.
![68684816-1b9da580-058f-11ea-95f3-eb0b1fb6d21f](https://user-images.githubusercontent.com/56734145/68782880-165c5b80-0660-11ea-828b-3febfe086921.jpg)
![68684828-20625980-058f-11ea-8968-1cc54f7a0c09](https://user-images.githubusercontent.com/56734145/68782898-1f4d2d00-0660-11ea-8941-9b26247e2003.jpg)


I hope, please suggest, because latest nebular version released with this issue.

html 
-----------
 <input [nbDatepicker]="formpicker" formControlName ="selectDate" [class.is-invalid]="selectDate.invalid && selectDate.touched" class="form-control" placeholder="dd-mm-yyyy"/>
        <nb-datepicker #formpicker [min]="min" [max]="max" format="dd.MM.yyyy"></nb-datepicker>
        <div *ngIf="selectDate.invalid && selectDate.touched">
            <small *ngIf="selectDate.errors?.required" class="text-danger">Select Date is required</small>
        </div> 

Ts file
----------
 this.min = this.dateService.addDay(this.dateService.today(), -3);
    this.max = this.dateService.addDay(this.dateService.today(), 1);

**Comment by cwmrowe** [comment]
I have been having issues with the datepicker too but I think I undertstand it now. 

Any time you import `NbDatepickerModule` and you want to use the format function you must include your format module (e.g. `NbMomentDateModule`) AFTER `NbDatepickerModule`. I believe this is because `NbDatepickerModule` provides `NbNativeDateService` (NatveDate) for use as the `NbDateService` by default, and in this case we want to override that with `NbMomentDateService` from `NbMomentDateModule`.

I think it would be simpler if Nebular made you choose the default `NbDateService`, rather than making `NbNativeDateService` default and forcing you to override it every time you include `NbDatepickerModule`.

**Comment by augustoicaro** [comment]
I made it work! I installed @nebular/date-fns with the version of nebular that I'm using `npm i --save @nebular/date-fns@5.0.0` (Change to the version that you use).  At my `app.module.ts` I added after `NbDatepickerModule.forRoot(),` the following line `NbDateFnsDateModule.forRoot({ format: 'dd/MM/yyyy' }),` (Change to the format that you want). Also, you need to add `NbDatepickerModule` in the imports of the module that you want to use, in my case was pages module `pages.module.ts`: 

```
@NgModule({
  imports: [
    ...
    NbDatepickerModule,
    ...
  ],
```

**Comment by RenanSchwyz** [comment]
@augustoicaro You're a life saver, your solution worked for me, thanks!

**Comment by CrankyTechGeek** [comment]
@augustoicaro This worked for me as well. My problem was with the "dd MMM yyyy" format. The different thing for me was that only Firefox marked it invalid, but it worked ok on Chrome. After using your solution it works ok on both browsers now. Thank you.

**Comment by alvearcoria** [comment]
@augustoicaro friend, what other libraries do you use or how is your configuration since I managed to change the format but the validation continues without accepting me.
example: 19/Aug/2023
This date does not validate it for me but if you put it directly and the validator only accepts me: Aug 18, 2023

**Comment by augustoicaro** [comment]
Hello @alvearcoria, besides the date-fns from Nebular 10  I use the regular date-fns.
```json
"@nebular/date-fns": "10.0.0",
"date-fns": "^2.29.3",
```
All my date manipulation is made with date-fns and the nebular package enables the same manipulation inside nebular.
