### ISSUE TITLE
userMenu call function

### ISSUE THREAD

**Issue by jogamod** [akveo/nebular#11]
By default HeaderComponent contains "userMenu = [{ title: 'Profile'}, { title: 'Log out'}];", how to add a click event to Log out to call function from Component?  I tried to itemClick(event, item) and menuClick(event, item) as I found in Documentation (https://akveo.github.io/nebular/#/docs/components/user-avatar) but none of them works.

**Comment by nnixaa** [comment]
Hey @jogamod would you mind sharing your code? As `<user (menuClick)="onMenuClick($even)">` should work.

**Comment by YukiDmZhao** [comment]
I meet to so problem, How to do? maybe have code example?

**Comment by YukiDmZhao** [comment]
<nb-user [menu]="userMenu" [name]="user?.name" [picture]="user?.picture"  (menuClick)="onMenuClick($even)"></nb-user>

**Comment by nnixaa** [comment]
@YukiDmZhao what errors are you getting?

**Comment by YukiDmZhao** [comment]
onMenuClick($even){
    console.log('$even======>',$even);
  }
$even======> undefined
can not run I want to function

**Comment by nnixaa** [comment]
@YukiDmZhao  it should be `$event` with `t` and the end in your template.

**Comment by miguelleitevieira** [comment]
@nnixaa I have a doubt.

I'm trying to add a function to the logout option.

userMenu = [
    { title: 'Profile' },
    { title: 'Log out', click: console.log('/login') }
  ];

But this runs when the class is instantiated. 

You know how I can solve this?

**Comment by sKaouech** [comment]
@miguelleitevieira 
you can do this : 
userMenu = [
{ title: 'Profile' },
{ title: 'Log out', link: '/login' }
];

**Comment by hosseinGanjyar** [comment]
@sKaouech very good tick...
I used of routerlink into logout function that has a problem and redirected to login page.

```
logOut() {
     this.authService.logout('email')
     this.router.navigate(['/auth/logout']);
  }
```

@nnixaa Why past my solution has a problem?

**Comment by at-phutranv2** [comment]
hi guys, I'm customizing my logout button, but don't want to edit in header neubular in node module file, my issue is same as this thread but difference because I create new auth route and module outside, I already created login page by copying html in neubular node_module file then create new ts and html file for my own ! But when doing logout task (because the button logout which contained in header but I dont want to edit the header in node module file ) the way I'm thinking creating new header folder outside and copy paste then call to my header file not in module. Is there any way to add function to logout button (in header component in node module ) without   edit it ??

**Comment by at-phutranv2** [comment]
how can I override userMenu title logout and add newfunction for logout button without edit in neubular node module ???
