### ISSUE TITLE
Opening NbSelect hides nb-layout-header

### ISSUE THREAD

**Issue by rhajizadeh** [akveo/nebular#1158]
### Issue type

**I'm submitting a**

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**
If you have nb-layout-header on a page and nb-select inside nb-layout-column and if page's height is bigger than your screen and you open the nb-select after scrolling, the nb-layout-header would disappear.

**Expected behavior:**
nb-layout-header shouldn't move or disappear after scrolling the page and opening the nb-select 

**Steps to reproduce:**
create nb-layout then inside it one nb-layout-header and one nb-layout-column. Then put a div Inside nb-layout-column with height bigger than the screen, so you can to scroll it then put a nb-select inside this div in a position that you have to scroll in order to get to it, then open then nb-select to see the issue.

**Related code:**
Please take a look at this StackBlitz code, keep in mind that you have to scroll first then open nb-select to see this behavior. 
 [StackBlitz nb-select-issue Project](https://stackblitz.com/edit/nb-select-issue)

**Comment by maihannijat** [comment]
I also confirm the bug - It is happening to my project as well.

**Comment by syamman** [comment]
Thats a feature. Not a bug. It will let the user focus on that selection once used it.

**Comment by dizco** [comment]
I'm not sure exactly why this bug is happening, but I notice that it's related to the fact that a style is added to the `html` tag with a `top` value in the negatives. The more you scroll down before opening the `nb-select`, the lower the `top` value is.

I tried to reproduce the issue in the official documentation examples and was unable to. Don't know what the difference is...

Anyone have an idea how we could fix this annoying bug?

**Comment by javaDeveloperKid** [comment]
I've got very similar issue. When the select is expanded my layout gets messed up. The following 4 pictures show:
1. Page not scrolled and City select not expanded.
2. Page not scrolled and City select expanded. Note the scroll bar that appears on the right.
3. Page was scrolled down in order to choose the brand.
4. Brand select expanded. Note that the header has disappeared and the blank, white space has appeared at the bottom.

Pic. 1.
![Screenshot at 2019-03-21 15:08:56](https://user-images.githubusercontent.com/25783196/54758590-bd314a80-4bec-11e9-897a-47cc0ebe6b44.png)

Pic. 2.
![Screenshot at 2019-03-21 15:09:00](https://user-images.githubusercontent.com/25783196/54758598-c15d6800-4bec-11e9-8e59-d566d85a747f.png)

Pic. 3.
![Screenshot at 2019-03-21 15:09:06](https://user-images.githubusercontent.com/25783196/54758607-c4f0ef00-4bec-11e9-9cec-e6fdbf27f5d6.png)

Pic. 4
![Screenshot at 2019-03-21 15:09:13](https://user-images.githubusercontent.com/25783196/54758612-c8847600-4bec-11e9-9728-ec98b4de49fe.png)
