### ISSUE TITLE
Unable to remove new icon from the Dashboard button in the menu

### ISSUE THREAD

**Issue by jainAdijain** [akveo/nebular#1220]
How to remove the "new" as marked in the image 

![image](https://user-images.githubusercontent.com/27722458/52411158-c49b0980-2b00-11e9-8fd7-432769599bb1.png)

**Comment by sukeshlaghate** [comment]
Hi @jainAdijain ,

You would need to access file @theme/layouts/sample/sample.layout.scss and comment out the section
starting at line 111 through 126 containing lines
```
    /deep/ nb-menu {
      & > .menu-items {
        & > .menu-item:first-child {
          .menu-title {
            &::after {
              content: 'new';
              color: nb-theme(color-white);
              margin-left: 1rem;
              background: nb-theme(color-danger);
              padding: 0 0.5rem;
              border-radius: nb-theme(radius);
              font-size: nb-theme(font-size-sm);
            }
          }
        }
      }
```
This would remove "new" label. 
@nnixaa Request you to refactor code to use badge instead of CSS,  so that users can easily remove  "new" label

With regards,
Sukesh.

**Comment by yggg** [comment]
Thanks for your help, sukeshlaghate. We'll remove this badge in the next release.
Closing as answered.
