### ISSUE TITLE
[Select] To add a search for items in NbSelectComponent

### ISSUE THREAD

**Issue by Kolpak86** [akveo/nebular#1350]
### Issue type

* [x] feature request

### Issue description

**Expected behavior:**
To add a search for items in NbSelectComponent. The expected behavior is shown in the image below.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/30974219/55542595-0ba41600-56d0-11e9-84fd-ebd121acf18e.gif)

**Comment by caiusCitiriga** [comment]
hey! Any news on this? Will this be released shortly? <3

**Comment by liujie20087349** [comment]
looking forward to this feature

**Comment by developer-cormatix** [comment]
any updates on this feature ???

**Comment by arjan-s** [comment]
Not talking on behalf of the project, but it's already in the latest beta of 5.0.0: https://akveo.github.io/nebular/5.0.0-beta.3/docs/components/autocomplete/overview
No idea when 5.0.0 will be released though.

**Comment by yggg** [comment]
Autocomplete component (#1947) is available in Nebular 5
https://akveo.github.io/nebular/docs/components/autocomplete/overview#nbautocompletedirective

**Comment by Kolpak86** [comment]
That's cool. Thank you, guys!!

**Comment by AntonGrekov** [comment]
I don't like such component architecture that is currently in nebular. 
It would be better that search field is in same list where all items are. 
And user is unable to enter anything in initial field. 

Because, oftenly, selected item is an object 
````json
{ id: number, value: string }
````
, and if user is able to enter any text in initial field you get a mess and need to catch situations where user enter something.
