### ISSUE TITLE
<nb-select> does not update the model when used with object.

### ISSUE THREAD

**Issue by aniketkadu2002** [akveo/nebular#1818]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [x] bug report
* [ ] feature request

### Issue description

**Current behavior:**

When using nb-select with object the model does not get updated with selected object.
In below example the list contains 2 items - test1 and test2. 
When selecting test1 from drop down the variable selectedItem should get updated with test1 object, however that does not work.

items = [{title: 'test1'}, {title: 'test2'}];
selectedItem;

`<nb-select [(selected)]="selectedItem">
	<nb-option *ngFor="let item of items" value="item">
	{{ item.title }}
	</nb-option>
</nb-select>`

**Expected behavior:**

The model should be updated with selected object value.

**Steps to reproduce:**

https://stackblitz.com/edit/github-kkt2hz-36zipg

**Related code:**

```
insert short code snippets here
```

### Other information:

**npm, node, OS, Browser**
```
<!--
Node, npm: `node --version` and `npm --version`
OS: Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Browser: Chrome/Safari/Firefox/etc?
-->
```

**Angular, Nebular**
`Angular 7.0.2` `Nebular 4.1.1`

```

**Comment by yggg** [comment]
Hi @aniketkadu2002, could you please update stackblitz link? It doesn't work.

**Comment by aniketkadu2002** [comment]
> Hi @aniketkadu2002, could you please update stackblitz link? It doesn't work.

Updated the Stackblitz URL - https://stackblitz.com/edit/github-kkt2hz-36zipg

**Comment by yggg** [comment]
I'm seeing two issues with referenced stackblitz.
First, missing `FormsModule` import in `HomeModule`. It's required since second select in `home.component.html` template uses `ngModule` binding.
Second, is option value bindings in `home.component.html` on lines `7` and `17`. It should be `[value]="item"` with square brackets not `value="item"`. The latter syntax is used when need to bind string `item` not an object. See Angular [docs](https://angular.io/guide/template-syntax#binding-target) for details.

After fixing issues above select works with objects as expected.

**Comment by aniketkadu2002** [comment]
@yggg It is working after making the changes you suggested. Thank you for your response.

**Comment by yggg** [comment]
Glad the issue resolved 🙂
