### ISSUE TITLE
Infinite List in Chat UI

### ISSUE THREAD

**Issue by Luca1991** [akveo/nebular#1870]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

It would be cool if we could have an "infinite list style" Chat UI, so we can get only the latest messages from the backend and then retieve the older messages only when the user scroll up the chat window.

I think that this would be useful also in other use-cases

Please let me know if this is something you will implement in the future, or if there is any work around to achieve this.

Thanks,
Luca

**Comment by amirhosein993** [comment]
hi! I did this for my project and its working fine. try it ;) 
instead of this.getPrivateChats method, write the code you want to load next page data
thanks to nebular team!
![component](https://user-images.githubusercontent.com/18518912/63090090-6b100d80-bf6f-11e9-8c17-c624cb801bca.PNG)
![html](https://user-images.githubusercontent.com/18518912/63090092-6b100d80-bf6f-11e9-8b56-57dd94e211e5.PNG)
![scss](https://user-images.githubusercontent.com/18518912/63090093-6b100d80-bf6f-11e9-8341-aed9d61b94c7.PNG)

**Comment by amirhosein993** [comment]
> ### Issue type
> **I'm submitting a ...** (check one with "x")
> 
> * [ ]  bug report
> * [x]  feature request
> 
> ### Issue description
> It would be cool if we could have an "infinite list style" Chat UI, so we can get only the latest messages from the backend and then retieve the older messages only when the user scroll up the chat window.
> 
> I think that this would be useful also in other use-cases
> 
> Please let me know if this is something you will implement in the future, or if there is any work around to achieve this.
> 
> Thanks,
> Luca

use my answer it will work for you :)

**Comment by Luca1991** [comment]
@amirhosein993 hey thank you for your reply! 
I'm currently in vacation, but I'll make sure to try your solution within some days and I'll let you know! Thank you very much!

**Comment by amirhosein993** [comment]
> @amirhosein993 hey thank you for your reply!
> I'm currently in vacation, but I'll make sure to try your solution within some days and I'll let you know! Thank you very much!

your welcome. have a good vacation.

**Comment by Luca1991** [comment]
@amirhosein993 sadly my vacation is over and I'm back to work! :sob: :smiley:  I've tested your solution and it is working perfectly! Thank you!
