### ISSUE TITLE
Nb-tabset. It would be nice to be able to provide a template to tab-title

### ISSUE THREAD

**Issue by dimaatkaev** [akveo/nebular#1915]
### Issue type

**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [ x] feature request

### Issue description

**Current behavior:**
a string can be provided to the tab-title only

**Expected behavior:**
a custom template can be provided to the tab-title only

**Comment by tomwilliamfranklin** [comment]
I know this issue is old - but any update to this? I am wanting to add more customizable badges to the tabs 😢 


> Any way to change the background and color of the tab-title??

Try this - make sure you place ng-deep at the start, this will apply the styling no matter the nested components generated by nebular: 

`::ng-deep .nb-theme-default nb-tabset .tab.active .tab-link {
   background-color: pink;
   color: green;
}`

**Comment by arpansac** [comment]
+1
More customizations for nb-tabset and nb-tab
