### ISSUE TITLE
Any way to center the text in a nb-card-header?

### ISSUE THREAD

**Issue by RoWEN-FCUB** [akveo/nebular#2046]
Hello, I'm trying to align the text inside a nb-card-header, so far without success. Is there a way to do this? I need the text aligned to the center of the card header.

Thanks for any help.

**Comment by AlecDr** [comment]
Hello, have you tried to use bootstrap align classes?
You could use the class 'text-center' in a wrapping div to center it horizontally, or 'my-auto' to center it vertically...

**Comment by RoWEN-FCUB** [comment]
> 
> 
> Hello, have you tried to use bootstrap align classes?
> You could use the class 'text-center' in a wrapping div to center it horizontally, or 'my-auto' to center it vertically...

THANKS!! A div with the class text-center did the job.

**Comment by emarbo** [comment]
Hello! Sorry for posting in an old issue. As far as I see, there's no relation between Nebular and Bootstrap. Is it recommended to install Bootstrap CSS and Nebular for these customizations? Or could we use anything different? (e.g. Tailwind CSS).

I'm unsure if installing a CSS library/tool could break things in Nebular.

**Comment by AlecDr** [comment]
Hey @emarbo,

I believe that back in the day the nebular template used bootstrap as a dependency, thats why the solution i gave worked for @RoWEN-FCUB, but looking now in [this commit](https://github.com/akveo/nebular/commit/f3f05cece1da7f5f8f2129916c8c233afe9340a5) it seems that they removed the bootstrap dependency.

Regarding the installation of a css library/tool, it believe that things would not work as expected since some css classes names could be used twice.

**Comment by emarbo** [comment]
HI @AlecDr, thanks for the quick reply and advice! Based on this, we'll start by writing standard CSS, and let's see if it works for us :+1:.

Regarding the tool, I remembered that Tailwind has a [prefix](https://tailwindcss.com/docs/configuration#prefix) configuration to prevent this collision issue. If needed, we'll probably use a framework that offers this feature to avoid undesired surprises
