### ISSUE TITLE
Toast Ref OnClose, OnClick

### ISSUE THREAD

**Issue by adamofig** [akveo/nebular#2595]
**I'm submitting a ...**  (check one with "x")

* [ ] bug report
* [X] feature request

### Issue description

**Current behavior:**

Toast events are not available  as in other components like dialogs, methods like onClick() or onClose()

**Expected behavior:**

Should add onClose or onClick subscribe events to Toast reference

**Comment by aleksey-korotkevich** [comment]
If somebody will ever come across this issue and it will be still not resolved, there's actually a hack to make it work

On click:
```
const toastRef = NbToastrService.show(...)
((<any>toastRef)['toastContainer']).nativeElement.addEventListener('click', () => {
  // do stuff here
})
```
It works because `toastRef` has container, but it is private, so we trick ts compiler with `any` and access that field. In the container we have `nativeElement` which is just `HTMLElement` and we can do with it anything that js can do, add listeners, get styles, etc

On close is tricker but something like this should work:
```
const toastRef = ((<any>NbToastrService.show(...))['toastContainer']).nativeElement
const options = {
    root: toastRef,
    rootMargin: '0px',
    threshold: 0
}

const observer = new IntersectionObserver(onCloseHandler, options);
```

Something like that. Maybe you can even prepare some wrapper around NbToastRef to prepare a better architecture
