### ISSUE TITLE
How to modify the login page style

### ISSUE THREAD

**Issue by haoyx** [akveo/nebular#26]
I think the text of the login page is changed to the company name

**Comment by nnixaa** [comment]
Hey @haoyx, thanks for your question. Could you be more specific, please?

**Comment by blankstar85** [comment]
Hey @nnixaa, I was looking at this last night to. I know the user said style, but maybe they meant the html?

I had the same question to modify the html. I'm trying to add a logo or company name to the sign in and register. As well as figure out to make a modal for the Terms and conditions, but it looks like the html is part of the nebular/Auth module and we would need to modify it in the npm package rather than being able to override it in the theme with something a little more custom if we have different signup info or etc.

**Comment by nnixaa** [comment]
@blankstar85 thanks for the details. Guys, please check out this issue https://github.com/akveo/nebular/issues/12. Generally, you are not limited to use these components out of node_modules. The auth module built in a modular way, meaning you can easily copy & modify any part of it. We will update a documentation in upcoming future for sure. Hope this helps!

**Comment by blankstar85** [comment]
@nnixaa Thanks for the info. I'll have to try figuring that out, Sorry for bothering you on this request. I didn't look at the closed requests. Almost did my due diligence here. Thanks!

**Comment by nnixaa** [comment]
No problem!
