### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by khurram-wasim** [akveo/nebular#407]
This is a feature request
Currently nebular does not support server side rendering
I followed this guideline:
https://github.com/angular/angular-cli/wiki/stories-universal-rendering
At the end I found out that nebular uses things which are not supported while rendering on the server side.
e.g. window, document, localstorage etc
Kindly fix this issue.

**Comment by denisobrienirl** [comment]
You might want to look into a work around discussed here - https://github.com/angular/universal/issues/830.

I have Nebular UI running in SSR setup with domino. There are other minor issues associate with it, but nothing that stops the application from running. See my server.ts here - https://github.com/akveo/nebular/issues/402 . Hope it helps.

**Comment by nnixaa** [comment]
Hi @tdespenza, you can open a new issue with the details of the issues you are having.

**Comment by Ballpin** [comment]
I found a solution for this.

1. Move source to [Angular Universal](https://angular.io/guide/universal)
2. Follow @AnthonyNahas instructions in [https://github.com/SebastianM/angular-google-maps/issues/1052](https://github.com/SebastianM/angular-google-maps/issues/1052) for each plugin thats complaining about "Unexpected import".
3. Use Domino if you need to. Normally is not suppose to be used because Node does not have window. Instead you are suppose to check if the platform is browser and then invoke localstorage in that if statement. See [this link for more information](https://medium.com/@zainzafar/localstorage-with-angular-universal-2a111fb4af72)

**Comment by neilhem** [comment]
There is also problem running in SSR because of window is not defined in intersection observer module
