### ISSUE TITLE
Create a Custom Theme

### ISSUE THREAD

**Issue by jwest80** [akveo/nebular#52]
Hello,

For starters, it looks like a really great project you have here.  The interface is great and I like the way everything is organized.  I am just recently trying to get familiar with everything (I had looked into ng2-admin a while back, but never pushed forward) and now have come across this.  I figured I would start by recreating one of my existing projects and have stumbled on the styling and themes.

I see documentation about how to setup the "built-in" cosmic and default themes.  Which work great (I just used the ngx-admin starter.)  How would I go about creating an entirely new theme?   Do we just create new built in themes or is there another way? 

I am hoping to understand what would be considered expected practice for this.

Thanks,
jwest80

**Comment by mathieu-neron** [comment]
Seconded, would be great to have documentation on this.

**Comment by mathieu-neron** [comment]
Was able to do this by following the advanced setup of https://akveo.github.io/nebular/#/docs/guides/enabling-theme-system :)

You could also mention that you can simply apply the theme's name in your theme module (instead of the default cosmic) isntead of having to use a themeService.

I also added my own theme.myThemeName.ts constant, like what was done for theme.default.ts and theme.cosmic.ts. and included in the theme module as well. Is this recommended?

**Comment by nnixaa** [comment]
@mathieu-neron you are absolutely right, we have to create this documentation and it is scheduled, we just need some time. The `theme.themeName.ts` file contains colors and variables used for JS plugins such as charts which cannot be styled using CSS and accept styles as JS objects.

**Comment by nnixaa** [comment]
Let's track it as #165.

**Comment by vineet1996** [comment]
hello im working on menu, so i want to change menu icon color , 
if i change globally using,
  text-hint-color: #ffff,
it will effect in all pages i just want to use in particular components
