### ISSUE TITLE
I couldn't found Nb Stepper into @nebular/theme v2.rc.10 

### ISSUE THREAD

**Issue by AbelValdez** [akveo/nebular#657]
Hello, 

I'm trying to use the newest components from nebular to keep the same format in my applications in particular **Stepper** Component, I have installed  **ngx-admin starter kit**  but I can not find it even installing **@nebular/theme v2.rc.10** 

Does some body knows how can I implement it?

**Comment by aefox** [comment]
@AbelValdez I just had the same issue while trying to play with the stepper.

It seems that the stepper and other new components which have just been added to `nebular 2.0.0-rc.10` are currently not imported by the `ngx-admin` project (you can look [here ](https://github.com/akveo/ngx-admin/blob/master/src/app/%40theme/theme.module.ts#L6)for what modules are currently imported).

So, in order to use it you'll have to update the same import list and add `NbStepperModule`. Once you import it you'll also have to declare it as part of the `NB_MODULES` ([here](https://github.com/akveo/ngx-admin/blob/master/src/app/%40theme/theme.module.ts#L55)) so it is picked up by angular.

So this issue is actually not related to `nebular` but with `ngx-admin`. Also, it is actually not an issue since `ngx-admin` is still on `nebular 2.0.0-rc.9`.

cc: @nnixaa This can be closed

**Comment by AbelValdez** [comment]
@aefox  Thanks for your answer, but what about the module (I mean the components files). Do I need to add them manually?

**Comment by Prefix1802** [comment]
@aefox 

Sorry for intruding, but my guess is that ngx admin is already on RC10.

Just have a look at package.json

**Comment by AbelValdez** [comment]
Ok, I already had my package with `"@nebular/theme": "2.0.0-rc.10"`  when I created the issue I couldn't see the stepper component files, but now I just did a `npm install ` and all the files appears into my project.

Thanks for all :+1:
