### ISSUE TITLE
Updating Nebular to 2.0.0 error at compiling

### ISSUE THREAD

**Issue by osrepository** [akveo/nebular#856]
### Compiling error

**I'm submitting a ...**  (check one with "x")

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
After updating to the new versión (2.0.0) and running the "ng serve" command, I get the next error:

ERROR in ./node_modules/@nebular/theme/styles/prebuilt/default.css (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/@nebular/theme/styles/prebuilt/default.css)
Module build failed: Error: Can't resolve '/Users/nixa/Development/Projects/Akveo/nebular/node_modules/@angular/cdk/overlay-prebuilt.css' in 'C:\Projects\Project\Project\ClientApp\node_modules\@nebular\theme\styles\prebuilt'

**Expected behavior:**
A compilation without errors.

**Steps to reproduce:**
Update the version.

I don't know if I'm the only one who is getting this error after updating. Maybe it's an error of mine and I apologize if that is the case.

Keep the great work!

**Comment by tomadj** [comment]
Hello ! 

Same problem. 
To fix this,  install @angular/cdk : 

`npm install --save @angular/cdk`

It's normal ? Material is now required ? 

Thank's

**Comment by osrepository** [comment]
I have @angular/cdk installed.
I guess the error comes in the URL '/Users/nixa/Development/Projects/Akveo/nebular/node_modules/@angular/cdk/overlay-prebuilt.css'
Is pointing to a nixa local directory or maybe I'm wrong, I don't really know.

**Comment by nnixaa** [comment]
Hey Guys, yes, since 2.0 Nebular requires Angular CDK (Component Development Kit) which is not Material per se (even though CDK is hoster on material website), and just a bunch of useful helpers to build better components 🙂 (here are some more details https://material.angular.io/cdk/categories). 
For more details on the upgrade steps and breaking changes please follow the [CHANGELOG](https://github.com/akveo/nebular/blob/master/CHANGELOG.md#steps).

As for the error - it looks really strange, we will look into. As a workaround, intead of the pre-built styles, you can use scss setup, here are some details on it in the documentaition https://akveo.github.io/nebular/docs/guides/enable-theme-system#normal-setup.

**Comment by benmizrahi** [comment]
same here

**Comment by benmizrahi** [comment]
Hi,

Please take a look at the cosmic.css, default.css, corporate.css filesL
@import url(/Users/nixa/Development/Projects/Akveo/nebular/node_modules/@angular/cdk/overlay-prebuilt.css);

I think that it's an hard coded in the scss file but i can't find where.

Anyway removing this import solved the build issue

**Comment by nnixaa** [comment]
2.0.1 is released with a fix for this issue.

**Comment by anuj509** [comment]
for those who are searching and solving same errors you can refer this link. I have forked this repo and fixed [starter-kit](https://github.com/anuj509/nebular.git)
